# route -n should look like
#0.0.0.0         10.162.0.1      0.0.0.0         UG    100    0        0 ens4
#10.0.130.0      10.0.254.71     255.255.255.0   UG    0      0        0 vlt_outside_br
#10.0.131.0      10.0.254.76     255.255.255.0   UG    0      0        0 vlt_outside_br
#10.0.250.0      10.0.254.71     255.255.254.0   UG    0      0        0 vlt_outside_br
#10.0.254.0      0.0.0.0         255.255.255.0   U     0      0        0 vlt_outside_br
#10.162.0.1      0.0.0.0         255.255.255.255 UH    100    0        0 ens4
#10.251.251.0    0.0.0.0         255.255.255.0   U     0      0        0 vlt_mgt_br
#172.16.0.0      0.0.0.0         255.255.255.248 U     0      0        0 collector_br
#192.168.122.0   0.0.0.0         255.255.255.0   U     0      0        0 virbr0

network:
    version: 2
    ethernets:
        collector_br:
            addresses:
                - 172.16.0.1/30
            routes:
                - to: 10.0.0.0/24
                  via: 172.16.0.2
        vlt_outside_br:
            addresses:
                - 10.0.254.1/24
            routes:
                - to: 10.0.250.0/23
                  via: 10.0.254.71
                - to: 10.0.130.0/24
                  via: 10.0.254.71
                - to: 10.0.131.0/24
                  via: 10.0.254.76
        vlt_mgt_br:
            addresses:
                - 10.251.251.1/24
